// Core movements (category 'core', region 'trunk'). Content only; see docs/ARCHITECTURE.md.
//
// Demo angles were solved numerically (figure.js normalizePose / solvePose / contactGaps) so the
// listed contact joints rest on the floor in every key pose, then reviewed on demo sheets
// (node tools/render-demos.mjs --cat core). Floor moves are drawn on a mat. Supine figures lie
// with the head at screen-left (torso 273: shoulders and hips both touch the floor). Moves that swap
// the supporting limb (bird dog, standing knee crunch) declare per-key `contacts`, and the standing
// knee crunch pins whichever foot is planted with per-key `anchor`s. Between sides, a lifted limb
// first hovers over its own spot so the weight shift is straight up and down (no skidding).

export default [
  {
    id: 'forearm-plank',
    name: 'Forearm Plank',
    say: 'Forearm plank',
    category: 'core',
    region: 'trunk',
    pattern: 'plank',
    impact: 'low',
    equipment: 'none',
    setup: 'Rest on your forearms with elbows under your shoulders.',
    cue: 'Hold one straight line from head to heels.',
    mistake: 'Letting the hips sag or pushing them high.',
    caution: 'Lower your knees to the floor whenever you need a break.',
    description: 'Side view. The figure holds a straight-body plank on its forearms and toes, breathing steadily.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearElbow', x: 146 },
      focus: ['core', 'shoulders'],
      props: [{ type: 'mat' }],
      contacts: ['nearElbow', 'nearHand', 'nearToe'],
      keys: [
        { pose: { torso: 82.5, head: 86.5, nearArm: [180, 90], nearLeg: [262.5, 262.5], nearFoot: 172 }, dur: 1.6, hold: 0.25 },
        { pose: { torso: 85, head: 89.5, nearArm: [180, 90], nearLeg: [261, 261], nearFoot: 172 }, dur: 1.6, hold: 0.25 },
      ],
    },
    alt: {
      name: 'Knee Forearm Plank',
      cue: 'Knees down, body straight from knees to head.',
      equipment: 'none',
      description: 'Side view. The figure holds a plank on its forearms and knees, feet lifted, body straight from knees to head.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearElbow', x: 146 },
        focus: ['core', 'shoulders'],
        props: [{ type: 'mat' }],
        contacts: ['nearElbow', 'nearHand', 'nearKnee'],
        keys: [
          { pose: { torso: 72.5, head: 76.5, nearArm: [180, 90], nearLeg: [252.5, 302], nearFoot: 287 }, dur: 1.6, hold: 0.25 },
          { pose: { torso: 75, head: 79.5, nearArm: [180, 90], nearLeg: [250, 302], nearFoot: 287 }, dur: 1.6, hold: 0.25 },
        ],
      },
    },
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    say: 'Side plank',
    category: 'core',
    region: 'trunk',
    pattern: 'side-plank',
    impact: 'low',
    equipment: 'none',
    setup: 'Lie on your side, elbow under your shoulder, legs stacked.',
    cue: 'Lift your hips into one long line.',
    mistake: 'Letting the hips sink toward the floor.',
    caution: 'Use the knee version if your shoulder needs a break.',
    switchSides: true,
    description: 'Front view. The figure holds a side plank on one forearm with the hips lifted and the top arm reaching up.',
    demo: {
      view: 'front',
      anchor: { joint: 'nearElbow', x: 145 },
      focus: ['core'],
      props: [{ type: 'mat' }],
      contacts: ['nearElbow', 'nearHand', 'nearToe'],
      keys: [
        { pose: { torso: 77.5, head: 77.5, nearArm: [180, 90], farArm: [12, 12], nearLeg: [257.5, 257.5], farLeg: [251.5, 251.5], nearFoot: 160, farFoot: 160 }, dur: 1.6, hold: 0.25 },
        { pose: { torso: 80, head: 80, nearArm: [180, 90], farArm: [12, 12], nearLeg: [255.5, 255.5], farLeg: [249.5, 249.5], nearFoot: 160, farFoot: 160 }, dur: 1.6, hold: 0.25 },
      ],
    },
    alt: {
      name: 'Knee Side Plank',
      cue: 'Bottom knee down, lift your hips off the floor.',
      equipment: 'none',
      switchSides: true,
      description: 'Front view. The figure holds a side plank on one forearm and the bottom knee, hips lifted and the top arm reaching up.',
      demo: {
        view: 'front',
        anchor: { joint: 'nearElbow', x: 149 },
        focus: ['core'],
        props: [{ type: 'mat' }],
        contacts: ['nearElbow', 'nearHand', 'nearKnee'],
        keys: [
          { pose: { torso: 69, head: 69, nearArm: [180, 90], farArm: [12, 12], nearLeg: [249, 275], farLeg: [242, 269], nearFoot: 250, farFoot: 250 }, dur: 1.6, hold: 0.25 },
          { pose: { torso: 71.5, head: 71.5, nearArm: [180, 90], farArm: [12, 12], nearLeg: [246, 275], farLeg: [239, 269], nearFoot: 250, farFoot: 250 }, dur: 1.6, hold: 0.25 },
        ],
      },
    },
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    say: 'Dead bugs',
    category: 'core',
    region: 'trunk',
    pattern: 'supine-hold',
    impact: 'low',
    equipment: 'none',
    setup: 'Lie on your back, arms up, knees bent over your hips.',
    cue: 'Lower opposite arm and leg, back stays down.',
    mistake: 'Letting the lower back arch off the floor.',
    caution: 'Keep your lower back supported; move only as far as you can control.',
    description: 'Side view. Lying on its back with the arms up and knees bent over the hips, the figure lowers one arm overhead and straightens the opposite leg, then alternates sides.',
    demo: {
      view: 'side',
      anchor: { joint: 'hip', x: 110 },
      focus: ['core'],
      props: [{ type: 'mat' }],
      contacts: ['head'],
      keys: [
        { pose: { torso: 273, head: 269, nearArm: [0, 0], farArm: [0, 0], nearLeg: [0, 90], farLeg: [0, 90], nearFoot: 40, farFoot: 40 }, dur: 0.6, hold: 0.15 },
        { pose: { torso: 273, head: 269, nearArm: [300, 300], farArm: [0, 0], nearLeg: [0, 90], farLeg: [66, 66], nearFoot: 40, farFoot: 0 }, dur: 0.6, hold: 0.25 },
        { pose: { torso: 273, head: 269, nearArm: [0, 0], farArm: [0, 0], nearLeg: [0, 90], farLeg: [0, 90], nearFoot: 40, farFoot: 40 }, dur: 0.6, hold: 0.15 },
        { pose: { torso: 273, head: 269, nearArm: [0, 0], farArm: [300, 300], nearLeg: [66, 66], farLeg: [0, 90], nearFoot: 0, farFoot: 40 }, dur: 0.6, hold: 0.25 },
      ],
    },
    alt: {
      name: 'Heel Taps',
      cue: 'Arms up, tap one heel to the floor, then switch.',
      equipment: 'none',
      description: 'Side view. Lying on its back with the arms up and knees bent over the hips, the figure lowers one foot at a time to tap the heel on the floor.',
      demo: {
        view: 'side',
        anchor: { joint: 'hip', x: 104 },
        focus: ['core'],
        props: [{ type: 'mat' }],
        contacts: ['head'],
        keys: [
          { pose: { torso: 273, head: 269, nearArm: [0, 0], farArm: [0, 0], nearLeg: [0, 90], farLeg: [0, 90], nearFoot: 40, farFoot: 40 }, dur: 0.55, hold: 0.15 },
          { pose: { torso: 273, head: 269, nearArm: [0, 0], farArm: [0, 0], nearLeg: [49.5, 141.5], farLeg: [0, 90], nearFoot: 100, farFoot: 40 }, dur: 0.55, hold: 0.2 },
          { pose: { torso: 273, head: 269, nearArm: [0, 0], farArm: [0, 0], nearLeg: [0, 90], farLeg: [0, 90], nearFoot: 40, farFoot: 40 }, dur: 0.55, hold: 0.15 },
          { pose: { torso: 273, head: 269, nearArm: [0, 0], farArm: [0, 0], nearLeg: [0, 90], farLeg: [49.5, 141.5], nearFoot: 40, farFoot: 100 }, dur: 0.55, hold: 0.2 },
        ],
      },
    },
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    say: 'Bird dogs',
    category: 'core',
    region: 'trunk',
    pattern: 'quadruped',
    impact: 'low',
    equipment: 'none',
    setup: 'Start on hands and knees, hands under your shoulders.',
    cue: 'Reach one arm forward and the opposite leg back.',
    mistake: 'Twisting the hips or arching the lower back.',
    caution: 'Place a folded towel under your knees for comfort.',
    description: 'Side view. On hands and knees, the figure reaches one arm forward and the opposite leg back, holds, returns, and alternates sides.',
    demo: {
      // Hip pinned. Each side: lift (hand straight up off its spot, knee drawn back), reach and hold,
      // lift back; then a diagonal weight shift hands the work to the other arm and leg.
      view: 'side',
      anchor: { joint: 'hip', x: 90 },
      focus: ['core'],
      props: [{ type: 'mat' }],
      contacts: ['farHand', 'nearKnee'],
      keys: [
        { pose: { torso: 76, head: 84, nearArm: [208.8, 148.6], farArm: [180, 180], nearLeg: [185, 284.5], farLeg: [200, 290], nearFoot: 185, farFoot: 200 }, dur: 0.6, hold: 0, tween: true },
        { pose: { torso: 76, head: 84, nearArm: [70, 70], farArm: [180, 180], nearLeg: [185, 284.5], farLeg: [258, 262], nearFoot: 185, farFoot: 185 }, dur: 0.6, hold: 0.35 },
        { pose: { torso: 76, head: 84, nearArm: [208.8, 148.6], farArm: [180, 180], nearLeg: [185, 284.5], farLeg: [200, 290], nearFoot: 185, farFoot: 200 }, dur: 0.3, hold: 0, tween: true },
        { pose: { torso: 76, head: 84, nearArm: [180, 180], farArm: [208.8, 148.6], nearLeg: [200, 290], farLeg: [185, 284.5], nearFoot: 200, farFoot: 185 }, dur: 0.6, hold: 0, tween: true, contacts: ['nearHand', 'farKnee'] },
        { pose: { torso: 76, head: 84, nearArm: [180, 180], farArm: [70, 70], nearLeg: [258, 262], farLeg: [185, 284.5], nearFoot: 185, farFoot: 185 }, dur: 0.6, hold: 0.35, contacts: ['nearHand', 'farKnee'] },
        { pose: { torso: 76, head: 84, nearArm: [180, 180], farArm: [208.8, 148.6], nearLeg: [200, 290], farLeg: [185, 284.5], nearFoot: 200, farFoot: 185 }, dur: 0.3, hold: 0, tween: true, contacts: ['nearHand', 'farKnee'] },
      ],
    },
    alt: {
      name: 'Bird Dog Leg Reach',
      cue: 'Keep both hands down and reach one leg back.',
      equipment: 'none',
      description: 'Side view. On hands and knees, the figure keeps both hands on the floor and reaches one leg straight back at a time, returning between reaches.',
      demo: {
        view: 'side',
        anchor: { joint: 'hip', x: 90 },
        focus: ['core'],
        props: [{ type: 'mat' }],
        contacts: ['nearHand', 'farHand', 'nearKnee'],
        keys: [
          { pose: { torso: 76, head: 84, nearArm: [180, 180], farArm: [180, 180], nearLeg: [185, 284.5], farLeg: [200, 290], nearFoot: 185, farFoot: 200 }, dur: 0.6, hold: 0, tween: true },
          { pose: { torso: 76, head: 84, nearArm: [180, 180], farArm: [180, 180], nearLeg: [185, 284.5], farLeg: [258, 262], nearFoot: 185, farFoot: 185 }, dur: 0.6, hold: 0.35 },
          { pose: { torso: 76, head: 84, nearArm: [180, 180], farArm: [180, 180], nearLeg: [185, 284.5], farLeg: [200, 290], nearFoot: 185, farFoot: 200 }, dur: 0.3, hold: 0, tween: true },
          { pose: { torso: 76, head: 84, nearArm: [180, 180], farArm: [180, 180], nearLeg: [200, 290], farLeg: [185, 284.5], nearFoot: 200, farFoot: 185 }, dur: 0.6, hold: 0, tween: true, contacts: ['nearHand', 'farHand', 'farKnee'] },
          { pose: { torso: 76, head: 84, nearArm: [180, 180], farArm: [180, 180], nearLeg: [258, 262], farLeg: [185, 284.5], nearFoot: 185, farFoot: 185 }, dur: 0.6, hold: 0.35, contacts: ['nearHand', 'farHand', 'farKnee'] },
          { pose: { torso: 76, head: 84, nearArm: [180, 180], farArm: [180, 180], nearLeg: [200, 290], farLeg: [185, 284.5], nearFoot: 200, farFoot: 185 }, dur: 0.3, hold: 0, tween: true, contacts: ['nearHand', 'farHand', 'farKnee'] },
        ],
      },
    },
  },
  {
    id: 'crunch',
    name: 'Crunch',
    say: 'Crunches',
    category: 'core',
    region: 'trunk',
    pattern: 'crunch',
    impact: 'low',
    equipment: 'none',
    setup: 'Lie on your back, knees bent, feet flat on the floor.',
    cue: 'Curl your shoulders up and reach toward your knees.',
    mistake: 'Leading with the chin instead of curling the upper back.',
    caution: 'Rest your head in your hands if your neck gets tired.',
    description: 'Side view. Lying on its back with the knees bent, the figure curls its head and shoulders up while reaching toward the knees, then lowers.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearAnkle', x: 155 },
      focus: ['core'],
      props: [{ type: 'mat' }],
      contacts: ['nearToe', 'nearAnkle'],
      keys: [
        { pose: { torso: 273, head: 273, nearArm: [98, 98], nearLeg: [46.5, 146.5], nearFoot: 100 }, dur: 0.9, hold: 0.15 },
        { pose: { torso: 305, head: 320, nearArm: [83.5, 83.5], nearLeg: [46, 146], nearFoot: 100 }, dur: 0.9, hold: 0.3 },
      ],
    },
    alt: {
      name: 'Supported Crunch',
      cue: 'Cradle your head and lift your shoulders a little.',
      equipment: 'none',
      description: 'Side view. Lying on its back with the knees bent and hands behind the head, the figure lifts the shoulders a small amount and lowers.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearAnkle', x: 155 },
        focus: ['core'],
        props: [{ type: 'mat' }],
        contacts: ['nearToe', 'nearAnkle'],
        keys: [
          { pose: { torso: 273, head: 271, nearArm: [333, 219], nearLeg: [46, 146], nearFoot: 100 }, dur: 0.9, hold: 0.15 },
          { pose: { torso: 292, head: 302, nearArm: [2.5, 247.5], nearLeg: [46, 146], nearFoot: 100 }, dur: 0.9, hold: 0.3 },
        ],
      },
    },
  },
  {
    id: 'bicycle-crunch',
    name: 'Bicycle Crunch',
    say: 'Bicycle crunches',
    category: 'core',
    region: 'trunk',
    pattern: 'rotation',
    impact: 'low',
    equipment: 'none',
    setup: 'Lie on your back, hands behind your head, knees lifted.',
    cue: 'Bring each elbow toward the opposite knee.',
    mistake: 'Pulling on the head or rushing the legs.',
    caution: 'Keep your lower back supported; aim the straight leg higher to ease off.',
    description: 'Side view. Lying with the shoulders lifted and hands behind the head, the figure draws one knee in as the other leg reaches out, alternating like pedaling.',
    demo: {
      view: 'side',
      anchor: { joint: 'hip', x: 96 },
      focus: ['core'],
      props: [{ type: 'mat' }],
      contacts: ['hip'],
      keys: [
        { pose: { torso: 300, head: 314, nearArm: [7.5, 257.5], farArm: [20.5, 261], nearLeg: [342, 75], farLeg: [62, 62], nearFoot: 25, farFoot: 20 }, dur: 0.85, hold: 0.15 },
        { pose: { torso: 303, head: 317, nearArm: [23.5, 264], farArm: [10.5, 260.5], nearLeg: [62, 62], farLeg: [342, 75], nearFoot: 20, farFoot: 25 }, dur: 0.85, hold: 0.15 },
      ],
    },
    alt: {
      name: 'Slow Bicycle',
      cue: 'Head down, slowly pedal one knee in, one leg out.',
      equipment: 'none',
      description: 'Side view. Lying on its back with the head down and arms by its sides, the figure slowly pedals the legs in and out.',
      demo: {
        view: 'side',
        anchor: { joint: 'hip', x: 111 },
        focus: ['core'],
        props: [{ type: 'mat' }],
        contacts: ['head', 'nearHand'],
        keys: [
          { pose: { torso: 273, head: 269, nearArm: [97.5, 97.5], farArm: [97.5, 97.5], nearLeg: [345, 75], farLeg: [42, 42], nearFoot: 30, farFoot: 10 }, dur: 1.35, hold: 0.15 },
          { pose: { torso: 273, head: 269, nearArm: [97.5, 97.5], farArm: [97.5, 97.5], nearLeg: [42, 42], farLeg: [345, 75], nearFoot: 10, farFoot: 30 }, dur: 1.35, hold: 0.15 },
        ],
      },
    },
  },
  {
    id: 'reverse-crunch',
    name: 'Reverse Crunch',
    say: 'Reverse crunches',
    category: 'core',
    region: 'trunk',
    pattern: 'crunch',
    impact: 'low',
    equipment: 'none',
    setup: 'Lie on your back, arms by your sides, knees over your hips.',
    cue: 'Draw your knees toward your chest, hips curl up.',
    mistake: 'Swinging the legs to throw the hips up.',
    caution: 'Keep the movement small if your lower back feels it.',
    description: 'Side view. Lying on its back with the knees bent over the hips, the figure draws the knees toward the chest so the hips curl slightly off the floor.',
    demo: {
      view: 'side',
      anchor: { joint: 'head', x: 46 },
      focus: ['core'],
      props: [{ type: 'mat' }],
      contacts: ['head', 'nearHand'],
      keys: [
        { pose: { torso: 273, head: 269, nearArm: [97.5, 97.5], nearLeg: [0, 90], nearFoot: 40 }, dur: 0.9, hold: 0.15 },
        { pose: { torso: 250, head: 266, nearArm: [100, 100], nearLeg: [322, 45], nearFoot: 0 }, dur: 0.9, hold: 0.3 },
      ],
    },
    alt: {
      name: 'Knee Tucks',
      cue: 'Tap both feet down, then draw your knees back in.',
      equipment: 'none',
      description: 'Side view. Lying on its back, the figure lowers both bent legs to tap the feet on the floor, then draws the knees back toward the chest.',
      demo: {
        view: 'side',
        anchor: { joint: 'head', x: 40 },
        focus: ['core'],
        props: [{ type: 'mat' }],
        contacts: ['head', 'nearHand'],
        keys: [
          { pose: { torso: 273, head: 269, nearArm: [97.5, 97.5], nearLeg: [345, 75], nearFoot: 30 }, dur: 0.9, hold: 0.15 },
          { pose: { torso: 273, head: 269, nearArm: [97.5, 97.5], nearLeg: [49.5, 141.5], nearFoot: 100 }, dur: 0.9, hold: 0.2 },
        ],
      },
    },
  },
  {
    id: 'leg-lowers',
    name: 'Leg Lowers',
    say: 'Leg lowers',
    category: 'core',
    region: 'trunk',
    pattern: 'supine-hold',
    impact: 'low',
    equipment: 'none',
    setup: 'Lie on your back, arms by your sides, legs straight up.',
    cue: 'Lower your legs slowly, keeping your back down.',
    mistake: 'Letting the lower back arch as the legs drop.',
    caution: 'Keep your lower back supported; stop higher or bend your knees to ease off.',
    description: 'Side view. Lying on its back with straight legs pointing up, the figure slowly lowers them toward the floor without touching, then raises them again.',
    demo: {
      view: 'side',
      anchor: { joint: 'hip', x: 98 },
      focus: ['core'],
      props: [{ type: 'mat' }],
      contacts: ['head', 'nearHand'],
      keys: [
        { pose: { torso: 273, head: 269, nearArm: [97.5, 97.5], nearLeg: [0, 0], farLeg: [0, 0], nearFoot: 330, farFoot: 330 }, dur: 1.6, hold: 0.2 },
        { pose: { torso: 273, head: 269, nearArm: [97.5, 97.5], nearLeg: [68, 68], farLeg: [68, 68], nearFoot: 40, farFoot: 40 }, dur: 1.1, hold: 0.3 },
      ],
    },
    alt: {
      name: 'Single-Leg Lowers',
      cue: 'Lower one leg at a time while the other stays up.',
      equipment: 'none',
      description: 'Side view. Lying on its back with both legs up, the figure lowers one straight leg at a time toward the floor and raises it again.',
      demo: {
        view: 'side',
        anchor: { joint: 'hip', x: 98 },
        focus: ['core'],
        props: [{ type: 'mat' }],
        contacts: ['head', 'nearHand'],
        keys: [
          { pose: { torso: 273, head: 269, nearArm: [97.5, 97.5], nearLeg: [0, 0], farLeg: [0, 0], nearFoot: 330, farFoot: 330 }, dur: 0.75, hold: 0.1 },
          { pose: { torso: 273, head: 269, nearArm: [97.5, 97.5], nearLeg: [70, 70], farLeg: [0, 0], nearFoot: 40, farFoot: 330 }, dur: 0.75, hold: 0.2 },
          { pose: { torso: 273, head: 269, nearArm: [97.5, 97.5], nearLeg: [0, 0], farLeg: [0, 0], nearFoot: 330, farFoot: 330 }, dur: 0.75, hold: 0.1 },
          { pose: { torso: 273, head: 269, nearArm: [97.5, 97.5], nearLeg: [0, 0], farLeg: [70, 70], nearFoot: 330, farFoot: 40 }, dur: 0.75, hold: 0.2 },
        ],
      },
    },
  },
  {
    id: 'standing-knee-crunch',
    name: 'Standing Knee Crunch',
    say: 'Standing knee crunches',
    category: 'core',
    region: 'trunk',
    pattern: 'rotation',
    impact: 'low',
    equipment: 'none',
    setup: 'Stand tall with your hands lightly behind your head.',
    cue: 'Lift a knee to the side and crunch toward it.',
    mistake: 'Pulling the head forward with the hands.',
    caution: 'Stand near a wall to steady yourself if needed.',
    description: 'Front view. The figure stands with hands behind its head, lifts one knee out to the side to about hip height and bends sideways to bring that elbow toward it, then alternates sides.',
    demo: {
      // The standing foot is pinned per key; the lifting foot hovers above its spot between reps so the
      // weight shifts cleanly. Hands stay clasped behind the head (arms solved to reach it).
      view: 'front',
      anchor: { joint: 'farAnkle', x: 92.5 },
      focus: ['core'],
      contacts: ['farToe', 'farAnkle'],
      keys: [
        { pose: { torso: 26, head: 22, nearArm: [79, -61.8], farArm: [-7.7, 127.4], nearLeg: [92, 172], farLeg: [-172.3, 173.4], nearFoot: 110, farFoot: -105 }, dur: 0.45, hold: 0.2 },
        { pose: { torso: 0, head: 0, nearArm: [35.9, -96.6], farArm: [-35.9, 96.6], nearLeg: [155.2, -153.8], farLeg: [-174.3, 174], nearFoot: 110, farFoot: -105 }, dur: 0.15, hold: 0, tween: true },
        { pose: { torso: 0, head: 0, nearArm: [35.9, -96.6], farArm: [-35.9, 96.6], nearLeg: [174.3, -174], farLeg: [-155.2, 153.8], nearFoot: 105, farFoot: -110 }, dur: 0.45, hold: 0, tween: true, anchor: { joint: 'nearAnkle', x: 107.5 }, contacts: ['nearToe', 'nearAnkle'] },
        { pose: { torso: -26, head: -22, nearArm: [7.7, -127.4], farArm: [-79, 61.8], nearLeg: [172.3, -173.4], farLeg: [-92, -172], nearFoot: 105, farFoot: -110 }, dur: 0.45, hold: 0.2, anchor: { joint: 'nearAnkle', x: 107.5 }, contacts: ['nearToe', 'nearAnkle'] },
        { pose: { torso: 0, head: 0, nearArm: [35.9, -96.6], farArm: [-35.9, 96.6], nearLeg: [174.3, -174], farLeg: [-155.2, 153.8], nearFoot: 105, farFoot: -110 }, dur: 0.15, hold: 0, tween: true, anchor: { joint: 'nearAnkle', x: 107.5 }, contacts: ['nearToe', 'nearAnkle'] },
        { pose: { torso: 0, head: 0, nearArm: [35.9, -96.6], farArm: [-35.9, 96.6], nearLeg: [155.2, -153.8], farLeg: [-174.3, 174], nearFoot: 110, farFoot: -105 }, dur: 0.45, hold: 0, tween: true },
      ],
    },
    alt: {
      name: 'Slow Side Crunch',
      cue: 'Lift your knee a little and lean gently toward it.',
      equipment: 'none',
      description: 'Front view. The figure stands with hands behind its head and slowly lifts one knee partway out to the side while leaning gently toward it, alternating sides.',
      demo: {
        view: 'front',
        anchor: { joint: 'farAnkle', x: 92.5 },
        focus: ['core'],
        contacts: ['farToe', 'farAnkle'],
        keys: [
          { pose: { torso: 12, head: 8, nearArm: [50.4, -84.9], farArm: [-25, 109.8], nearLeg: [135, 172], farLeg: [-172.3, 173.4], nearFoot: 110, farFoot: -105 }, dur: 0.6, hold: 0.25 },
          { pose: { torso: 0, head: 0, nearArm: [35.9, -96.6], farArm: [-35.9, 96.6], nearLeg: [157, -155.6], farLeg: [-174.3, 174], nearFoot: 110, farFoot: -105 }, dur: 0.2, hold: 0, tween: true },
          { pose: { torso: 0, head: 0, nearArm: [35.9, -96.6], farArm: [-35.9, 96.6], nearLeg: [174.3, -174], farLeg: [-157, 155.6], nearFoot: 105, farFoot: -110 }, dur: 0.6, hold: 0, tween: true, anchor: { joint: 'nearAnkle', x: 107.5 }, contacts: ['nearToe', 'nearAnkle'] },
          { pose: { torso: -12, head: -8, nearArm: [25, -109.8], farArm: [-50.4, 84.9], nearLeg: [172.3, -173.4], farLeg: [-135, -172], nearFoot: 105, farFoot: -110 }, dur: 0.6, hold: 0.25, anchor: { joint: 'nearAnkle', x: 107.5 }, contacts: ['nearToe', 'nearAnkle'] },
          { pose: { torso: 0, head: 0, nearArm: [35.9, -96.6], farArm: [-35.9, 96.6], nearLeg: [174.3, -174], farLeg: [-157, 155.6], nearFoot: 105, farFoot: -110 }, dur: 0.2, hold: 0, tween: true, anchor: { joint: 'nearAnkle', x: 107.5 }, contacts: ['nearToe', 'nearAnkle'] },
          { pose: { torso: 0, head: 0, nearArm: [35.9, -96.6], farArm: [-35.9, 96.6], nearLeg: [157, -155.6], farLeg: [-174.3, 174], nearFoot: 110, farFoot: -105 }, dur: 0.6, hold: 0, tween: true },
        ],
      },
    },
  },
];
