// Lower-body movements — see docs/ARCHITECTURE.md (Movement schema, Demo schema).
//
// Pose angles were solved numerically so planted feet stay put through every key: split stances,
// wide stances and the bridge keep both contact points fixed, and keys marked `tween: true` are
// in-between poses that keep the feet planted during long transitions (they are skipped in the
// reduced-motion key strip). `dx` values pin the planted foot when the anchor foot is the moving one.
// If you edit a leg angle, re-check contacts with tools/render-demos.mjs.

export default [
  // 1 ----------------------------------------------------------------- squat
  {
    id: 'squat',
    name: 'Squat',
    say: 'Squats',
    category: 'lower',
    region: 'legs',
    pattern: 'squat',
    impact: 'low',
    equipment: 'none',
    setup: 'Stand tall with feet about shoulder-width apart, toes turned slightly out.',
    cue: 'Sit your hips back and down, then stand tall.',
    mistake: 'Letting the heels lift or the knees fall inward.',
    caution: 'Lower only as far as feels comfortable for your knees.',
    description: 'Side view. The figure sits the hips back and down until the thighs are about level with the floor, arms reaching forward for balance, then stands tall.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearAnkle', x: 98 },
      focus: ['legs'],
      contacts: ['nearToe', 'nearAnkle'],
      keys: [
        { pose: { torso: 0, nearArm: [176, 176], farArm: [184, 184] }, dur: 1.3, hold: 0.25 },
        { pose: { torso: 34, head: 20, nearArm: [88, 92], farArm: [93, 97], nearLeg: [97, 208] }, dur: 1, hold: 0.2 },
      ],
    },
    alt: {
      name: 'Half Squat',
      cue: 'Lower halfway, then stand. Hold a wall if you like.',
      equipment: 'none',
      description: 'Side view. The figure bends the knees and sits the hips back about halfway, arms forward, then stands tall.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearAnkle', x: 100 },
        focus: ['legs'],
        contacts: ['nearToe', 'nearAnkle'],
        keys: [
          { pose: { torso: 0, nearArm: [176, 176], farArm: [184, 184] }, dur: 1.1, hold: 0.25 },
          { pose: { torso: 20, head: 12, nearArm: [100, 104], farArm: [104, 108], nearLeg: [128, 196] }, dur: 0.9, hold: 0.2 },
        ],
      },
    },
  },

  // 2 ----------------------------------------------------------------- sumo-squat
  {
    id: 'sumo-squat',
    name: 'Sumo Squat',
    say: 'Sumo squats',
    category: 'lower',
    region: 'legs',
    pattern: 'squat',
    impact: 'low',
    equipment: 'none',
    setup: 'Stand with feet wide and toes turned out, hands on hips.',
    cue: 'Push your knees out over your toes as you lower.',
    mistake: 'Letting the knees fall inward past the toes.',
    description: 'Front view. From a wide stance with toes turned out, the figure bends both knees outward and lowers the hips straight down, then stands back up.',
    demo: {
      view: 'front',
      anchor: { joint: 'hip', x: 100 },
      focus: ['legs'],
      contacts: ['nearToe', 'farToe'],
      keys: [
        { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [149.1, 160.3], farLeg: [210.9, 199.7], nearFoot: 112 }, dur: 0.65, hold: 0.25, ease: 'in' },
        { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [120.1, 182.7], farLeg: [239.8, 177.1], nearFoot: 112, dx: -0.2 }, dur: 0.65, hold: 0, ease: 'out', tween: true },
        { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [100, 189.2], farLeg: [260, 170.8], nearFoot: 112 }, dur: 0.5, hold: 0.2, ease: 'in' },
        { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [120.9, 182.7], farLeg: [239.1, 177.6], nearFoot: 112 }, dur: 0.5, hold: 0, ease: 'out', tween: true },
      ],
    },
    alt: {
      name: 'Half Sumo Squat',
      cue: 'Lower only partway, knees pointing over your toes.',
      equipment: 'none',
      description: 'Front view. From a wide stance the figure bends the knees outward a little, lowering the hips partway, then stands.',
      demo: {
        view: 'front',
        anchor: { joint: 'hip', x: 100 },
        focus: ['legs'],
        contacts: ['nearToe', 'farToe'],
        keys: [
          { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [151.5, 162.8], farLeg: [208.5, 197.2], nearFoot: 112 }, dur: 0.55, hold: 0.25, ease: 'in' },
          { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [135.3, 176.8], farLeg: [224.7, 183.2], nearFoot: 112 }, dur: 0.55, hold: 0, ease: 'out', tween: true },
          { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [125.6, 183.4], farLeg: [234.4, 176.6], nearFoot: 112 }, dur: 0.45, hold: 0.2, ease: 'in' },
          { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [135.3, 176.8], farLeg: [224.7, 183.2], nearFoot: 112 }, dur: 0.45, hold: 0, ease: 'out', tween: true },
        ],
      },
    },
  },

  // 3 ----------------------------------------------------------------- reverse-lunge
  {
    id: 'reverse-lunge',
    name: 'Reverse Lunge',
    say: 'Reverse lunges',
    category: 'lower',
    region: 'legs',
    pattern: 'lunge',
    impact: 'low',
    equipment: 'none',
    setup: 'Stand tall, feet hip-width apart, hands on hips.',
    cue: 'Step back and lower until both knees bend.',
    mistake: 'Letting the front knee drift inward.',
    caution: 'Shorten the step if your knees complain.',
    description: 'Side view. The figure steps one foot back and lowers the back knee toward the floor, then steps forward to standing and repeats with the other leg.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearAnkle', x: 116 },
      focus: ['legs'],
      contacts: ['farToe'],
      keys: [
        { pose: { torso: 0, nearArm: [222, 127] }, dur: 0.55, hold: 0.15, ease: 'in' },
        { pose: { torso: 4, nearArm: [226, 131], nearLeg: [184.4, 234.5], farLeg: [132, 180], nearFoot: 103, farFoot: 100, dx: -62.1 }, dur: 0.55, hold: 0, ease: 'out', tween: true },
        { pose: { torso: 8, nearArm: [230, 135], nearLeg: [187.7, 272.5], farLeg: [100, 193], nearFoot: 128, farFoot: 100, dx: -72.3 }, dur: 0.55, hold: 0.2, ease: 'in' },
        { pose: { torso: 4, nearArm: [226, 131], nearLeg: [184.4, 234.5], farLeg: [132, 180], nearFoot: 103, farFoot: 100, dx: -62.1 }, dur: 0.5, hold: 0, ease: 'out', tween: true },
        { pose: { torso: 0, nearArm: [222, 127] }, dur: 1.1, hold: 0.15 },
        { pose: { torso: 8, nearArm: [230, 135], nearLeg: [100, 193], farLeg: [187.7, 272.5], farFoot: 128 }, dur: 1.05, hold: 0.2 },
      ],
    },
    alt: {
      name: 'Split-Stance Dip',
      cue: 'Hold a wall, bend both knees a little, then rise.',
      equipment: 'wall',
      switchSides: true,
      description: 'Side view. Standing in a short split stance with both hands on a wall, the figure bends both knees a small amount and rises again.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearAnkle', x: 112 },
        props: [{ type: 'wall', x: 143, side: 'right' }],
        focus: ['legs'],
        contacts: ['nearToe', 'nearAnkle', 'farToe'],
        keys: [
          { pose: { torso: 2, nearArm: [113.2, 70.9], farArm: [113.2, 70.9], nearLeg: [148.3, 174.6], farLeg: [195.8, 223.9], farFoot: 128 }, dur: 0.55, hold: 0.2, ease: 'in' },
          { pose: { torso: 3, nearArm: [106.7, 64.3], farArm: [106.7, 64.3], nearLeg: [136.7, 181.9], farLeg: [185.8, 235.7], farFoot: 128 }, dur: 0.55, hold: 0, ease: 'out', tween: true },
          { pose: { torso: 4, nearArm: [98.3, 60], farArm: [98.3, 60], nearLeg: [125.3, 189.8], farLeg: [180.8, 247.4], farFoot: 128 }, dur: 0.45, hold: 0.2, ease: 'in' },
          { pose: { torso: 3, nearArm: [106.7, 64.3], farArm: [106.7, 64.3], nearLeg: [136.6, 183], farLeg: [186.9, 235.7], farFoot: 128, dx: 0.1 }, dur: 0.45, hold: 0, ease: 'out', tween: true },
        ],
      },
    },
  },

  // 4 ----------------------------------------------------------------- split-squat
  {
    id: 'split-squat',
    name: 'Split Squat',
    say: 'Split squats',
    category: 'lower',
    region: 'legs',
    pattern: 'lunge',
    impact: 'low',
    equipment: 'none',
    setup: 'Take a long step forward, back heel lifted, hands on hips.',
    cue: 'Lower straight down, then press up through the front foot.',
    mistake: 'Leaning far forward or letting the front heel lift.',
    caution: 'Keep the depth comfortable for your knees.',
    switchSides: true,
    description: 'Side view. In a split stance with the back heel raised, the figure lowers straight down until the back knee nears the floor, then rises. Feet stay in place.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearAnkle', x: 128 },
      focus: ['legs'],
      contacts: ['nearToe', 'nearAnkle', 'farToe'],
      keys: [
        { pose: { torso: 3, nearArm: [225, 130], nearLeg: [147.8, 168.7], farLeg: [202.1, 223.1], farFoot: 130 }, dur: 0.65, hold: 0.2, ease: 'in' },
        { pose: { torso: 5.5, nearArm: [227.5, 132.5], nearLeg: [124.4, 184.9], farLeg: [186.6, 247.3], farFoot: 130 }, dur: 0.65, hold: 0, ease: 'out', tween: true },
        { pose: { torso: 8, nearArm: [230, 135], nearLeg: [103, 194], farLeg: [182.8, 270.7], farFoot: 130 }, dur: 0.5, hold: 0.2, ease: 'in' },
        { pose: { torso: 5.5, nearArm: [227.5, 132.5], nearLeg: [124, 190.1], farLeg: [191.4, 247.6], farFoot: 130, dx: 0.2 }, dur: 0.5, hold: 0, ease: 'out', tween: true },
      ],
    },
    alt: {
      name: 'Supported Split Squat',
      cue: 'Hold a wall and lower only partway.',
      equipment: 'wall',
      description: 'Side view. In a split stance with one hand on a wall in front, the figure lowers partway and rises again.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearAnkle', x: 116 },
        props: [{ type: 'wall', x: 146, side: 'right' }],
        focus: ['legs'],
        contacts: ['nearToe', 'nearAnkle', 'farToe'],
        keys: [
          { pose: { torso: 2, nearArm: [115.1, 87.7], farArm: [224, 129], nearLeg: [142.8, 176.2], farLeg: [198.9, 227.6], farFoot: 130 }, dur: 0.6, hold: 0.2, ease: 'in' },
          { pose: { torso: 3, nearArm: [110.1, 74.1], farArm: [225, 130], nearLeg: [128.7, 187.3], farLeg: [189.5, 244], farFoot: 130 }, dur: 0.6, hold: 0, ease: 'out', tween: true },
          { pose: { torso: 4, nearArm: [100, 65.6], farArm: [226, 131], nearLeg: [114.1, 192.7], farLeg: [183.1, 259.3], farFoot: 130 }, dur: 0.5, hold: 0.2, ease: 'in' },
          { pose: { torso: 3, nearArm: [110.1, 74.1], farArm: [225, 130], nearLeg: [128.6, 182.8], farLeg: [185.8, 243.4], farFoot: 130, dx: 0.1 }, dur: 0.5, hold: 0, ease: 'out', tween: true },
        ],
      },
    },
  },

  // 5 ----------------------------------------------------------------- side-lunge
  {
    id: 'side-lunge',
    name: 'Side Lunge',
    say: 'Side lunges',
    category: 'lower',
    region: 'legs',
    pattern: 'lateral',
    impact: 'low',
    equipment: 'none',
    setup: 'Stand with feet wide apart, toes forward, hands on hips.',
    cue: 'Shift to one side, bend that knee, keep the other straight.',
    mistake: 'Letting the bent knee cave inward or the heel lift.',
    caution: 'Use a narrower stance if the stretch feels too deep.',
    description: 'Front view. From a wide stance the figure shifts the hips to one side, bending that knee while the other leg stays straight, returns to center, then switches sides.',
    demo: {
      view: 'front',
      anchor: { joint: 'nearAnkle', x: 150 },
      focus: ['legs'],
      contacts: ['nearToe', 'farToe'],
      keys: [
        { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [107.5, 198.4], farLeg: [236.8, 226.6] }, dur: 0.7, hold: 0.25, ease: 'in' },
        { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [122.7, 173.5], farLeg: [228.2, 209.6], dx: -0.3 }, dur: 0.45, hold: 0, ease: 'linear', tween: true },
        { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [132.4, 148.5], farLeg: [237.9, 185.7], dx: 0.2 }, dur: 0.7, hold: 0, ease: 'out', tween: true },
        { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [123.2, 133.4], farLeg: [252.5, 161.6] }, dur: 0.7, hold: 0.25, ease: 'in' },
        { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [133.3, 149.4], farLeg: [236.3, 187.5], dx: -0.2 }, dur: 0.45, hold: 0, ease: 'linear', tween: true },
        { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [122.2, 175.9], farLeg: [226.8, 212.7], dx: -0.4 }, dur: 0.7, hold: 0, ease: 'out', tween: true },
      ],
    },
    alt: {
      name: 'Shallow Side Lunge',
      cue: 'Shift side to side and bend the knee only a little.',
      equipment: 'none',
      description: 'Front view. From a moderately wide stance the figure shifts gently side to side with a small knee bend.',
      demo: {
        view: 'front',
        anchor: { joint: 'nearAnkle', x: 144 },
        focus: ['legs'],
        contacts: ['nearToe', 'farToe'],
        keys: [
          { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [128.5, 183.1], farLeg: [221, 210.8] }, dur: 0.65, hold: 0.25, ease: 'in' },
          { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [135.1, 170.4], farLeg: [218, 204.8], dx: 0.2 }, dur: 0.42, hold: 0, ease: 'linear', tween: true },
          { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [143.2, 155.5], farLeg: [223.4, 191], dx: -0.2 }, dur: 0.65, hold: 0, ease: 'out', tween: true },
          { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [139, 149.2], farLeg: [231.5, 176.9] }, dur: 0.65, hold: 0.25, ease: 'in' },
          { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [142.2, 156.2], farLeg: [224, 190.6], dx: -0.2 }, dur: 0.42, hold: 0, ease: 'linear', tween: true },
          { pose: { torso: 0, nearArm: [139.8, 222.7], nearLeg: [136.8, 169.2], farLeg: [215.2, 206.7] }, dur: 0.65, hold: 0, ease: 'out', tween: true },
        ],
      },
    },
  },

  // 6 ----------------------------------------------------------------- good-morning
  {
    id: 'good-morning',
    name: 'Good Morning',
    say: 'Good mornings',
    category: 'lower',
    region: 'legs',
    pattern: 'hinge',
    impact: 'low',
    equipment: 'none',
    setup: 'Stand tall, feet hip-width apart, arms crossed on your chest.',
    cue: 'Push hips back and tip forward with a flat back.',
    mistake: 'Rounding the back or bending the knees into a squat.',
    caution: 'Only hinge as far as you can keep your back flat.',
    description: 'Side view. With arms crossed and knees soft, the figure pushes the hips back and tips the chest forward with a flat back, then stands tall.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearAnkle', x: 96 },
      focus: ['glutes', 'back'],
      contacts: ['nearToe', 'nearAnkle'],
      keys: [
        { pose: { torso: 0, nearArm: [160, 345], farArm: [157, 342], nearLeg: [177, 183] }, dur: 1.4, hold: 0.2 },
        { pose: { torso: 72, nearArm: [232, 417], farArm: [229, 414], nearLeg: [160, 186] }, dur: 1.1, hold: 0.2 },
      ],
    },
    alt: {
      name: 'Hip Hinge',
      cue: 'Slide your hands down your thighs as you hinge.',
      equipment: 'none',
      description: 'Side view. With hands on the front of the thighs, the figure pushes the hips back and tips forward partway, hands sliding toward the knees, then stands.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearAnkle', x: 96 },
        focus: ['glutes', 'back'],
        contacts: ['nearToe', 'nearAnkle'],
        keys: [
          { pose: { torso: 0, nearArm: [182.6, 153.8], farArm: [184.6, 155.8], nearLeg: [176, 184] }, dur: 1.2, hold: 0.2 },
          { pose: { torso: 58, nearArm: [221.4, 189], farArm: [223.4, 191], nearLeg: [163, 186] }, dur: 1, hold: 0.2 },
        ],
      },
    },
  },

  // 7 ----------------------------------------------------------------- glute-bridge
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    say: 'Glute bridges',
    category: 'lower',
    region: 'legs',
    pattern: 'bridge',
    impact: 'low',
    equipment: 'none',
    setup: 'Lie on your back, knees bent, feet flat and hip-width apart.',
    cue: 'Press through your heels and lift your hips.',
    mistake: 'Arching the lower back instead of squeezing the glutes.',
    description: 'Side view. Lying on the back with knees bent, the figure lifts the hips until the body forms a straight line from shoulders to knees, then lowers.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearAnkle', x: 150 },
      props: [{ type: 'mat' }],
      focus: ['glutes', 'core'],
      contacts: ['head', 'nearHand', 'nearToe', 'nearAnkle'],
      keys: [
        { pose: { torso: 273, head: 269, nearArm: [96, 98], nearLeg: [42.3, 151.4] }, dur: 1, hold: 0.3 },
        { pose: { torso: 249.5, head: 275, nearArm: [96, 98], nearLeg: [69.3, 163.9] }, dur: 1.2, hold: 0.5 },
      ],
    },
    alt: {
      name: 'Small Bridge',
      cue: 'Lift your hips a little and pause.',
      equipment: 'none',
      description: 'Side view. Lying on the back with knees bent, the figure lifts the hips a small amount, pauses, then lowers.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearAnkle', x: 150 },
        props: [{ type: 'mat' }],
        focus: ['glutes', 'core'],
        contacts: ['head', 'nearHand', 'nearToe', 'nearAnkle'],
        keys: [
          { pose: { torso: 273, head: 269, nearArm: [96, 98], nearLeg: [42.3, 151.4] }, dur: 0.9, hold: 0.3 },
          { pose: { torso: 260, head: 273, nearArm: [96, 98], nearLeg: [57, 161.3] }, dur: 1, hold: 0.9 },
        ],
      },
    },
  },

  // 8 ----------------------------------------------------------------- wall-sit
  {
    id: 'wall-sit',
    name: 'Wall Sit',
    category: 'lower',
    region: 'legs',
    pattern: 'squat',
    impact: 'low',
    equipment: 'wall',
    setup: 'Stand with your back to a wall, feet out in front, hip-width apart.',
    cue: 'Keep your back flat on the wall and breathe.',
    mistake: 'Letting the knees drift past the toes or the back leave the wall.',
    caution: 'Sit only as low as feels comfortable for your knees.',
    description: 'Side view. The figure rests its back against a wall with knees bent and thighs about level with the floor, hands resting on the thighs, breathing steadily.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearAnkle', x: 128 },
      props: [{ type: 'wall', x: 79.2, side: 'left' }],
      focus: ['legs'],
      contacts: ['nearToe', 'nearAnkle'],
      keys: [
        { pose: { torso: 2, head: 2, nearArm: [166.3, 111.7], farArm: [169.3, 114.7], nearLeg: [90, 180] }, dur: 1.7, hold: 0 },
        { pose: { torso: 4.5, head: 7.5, nearArm: [172.5, 107.7], farArm: [175.5, 110.7], nearLeg: [88.2, 180] }, dur: 1.7, hold: 0 },
      ],
    },
    alt: {
      name: 'High Wall Sit',
      cue: 'Bend your knees only slightly and hold.',
      equipment: 'wall',
      description: 'Side view. The figure leans its back against a wall with a small knee bend, hands on the thighs, breathing steadily.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearAnkle', x: 128 },
        props: [{ type: 'wall', x: 87.4, side: 'left' }],
        focus: ['legs'],
        contacts: ['nearToe', 'nearAnkle'],
        keys: [
          { pose: { torso: 2, head: 2, nearArm: [180.3, 140.8], farArm: [183.3, 143.8], nearLeg: [128, 180] }, dur: 1.7, hold: 0 },
          { pose: { torso: 4.5, head: 7.5, nearArm: [181.3, 141.3], farArm: [184.3, 144.3], nearLeg: [125.8, 181.4] }, dur: 1.7, hold: 0 },
        ],
      },
    },
  },

  // 9 ----------------------------------------------------------------- calf-raise
  {
    id: 'calf-raise',
    name: 'Calf Raise',
    say: 'Calf raises',
    category: 'lower',
    region: 'legs',
    pattern: 'calf',
    impact: 'low',
    equipment: 'none',
    setup: 'Stand tall, feet hip-width apart, hands on hips.',
    cue: 'Rise onto the balls of your feet, then lower slowly.',
    mistake: 'Rolling onto the outer edges of the feet.',
    description: 'Side view. Standing tall, the figure lifts both heels so the body rises onto the balls of the feet, pauses, then lowers the heels.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearToe', x: 112 },
      focus: ['calves'],
      contacts: ['nearToe'],
      keys: [
        { pose: { torso: 0, nearArm: [222, 127], farArm: [219, 124], nearFoot: 100 }, dur: 0.9, hold: 0.2 },
        { pose: { torso: 0, nearArm: [222, 127], farArm: [219, 124], nearFoot: 148 }, dur: 1.1, hold: 0.35 },
      ],
    },
    alt: {
      name: 'Supported Calf Raise',
      cue: 'Rest your hands on a wall and rise onto your toes.',
      equipment: 'wall',
      description: 'Side view. Facing a wall with hands resting on it, the figure lifts both heels and lowers them slowly.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearToe', x: 88 },
        props: [{ type: 'wall', x: 128, side: 'right' }],
        focus: ['calves'],
        contacts: ['nearToe'],
        keys: [
          { pose: { torso: 0, nearArm: [118.8, 75], farArm: [118.8, 75], nearFoot: 100 }, dur: 0.9, hold: 0.2 },
          { pose: { torso: 0, nearArm: [139.7, 77.8], farArm: [139.7, 77.8], nearFoot: 148 }, dur: 1.1, hold: 0.35 },
        ],
      },
    },
  },
];
