// Upper-body movements. See docs/ARCHITECTURE.md (Movement schema, Demo schema).
// Angles were solved numerically so planted hands, toes and knees stay put through each rep.
// Keys marked `tween: true` are in-between poses that keep contacts honest mid-motion; they are
// left out of the reduced-motion key strip.
export default [
  {
    id: 'push-up',
    name: 'Push-up',
    say: 'Push-ups',
    category: 'upper',
    region: 'upper',
    impact: 'low',
    pattern: 'push',
    equipment: 'none',
    setup: 'Start in a high plank, hands under your shoulders.',
    cue: 'Lower your chest as one unit, then press away.',
    mistake: 'Letting the hips sag or pike up.',
    caution: 'Spread your fingers wide to share the load on your wrists.',
    description: 'A figure in a straight-body plank bends the elbows back to lower the chest toward the floor, then presses back up.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearHand', x: 128 },
      focus: ['chest', 'arms'],
      contacts: ['nearHand', 'nearToe'],
      keys: [
        { pose: { torso: 71, nearArm: [190, 190], nearLeg: [251, 251], nearFoot: 170 }, dur: 0.15, hold: 0.2, ease: 'in' },
        { pose: { torso: 73, nearLeg: [253, 253], nearFoot: 170.5, nearArm: [212, 171] }, dur: 0.26, hold: 0, ease: 'linear', tween: true },
        { pose: { torso: 78, nearLeg: [258, 258], nearFoot: 172, nearArm: [239.5, 157] }, dur: 0.69, hold: 0, ease: 'out', tween: true },
        { pose: { torso: 87, nearLeg: [267, 267], nearFoot: 174, nearArm: [279.5, 156] }, dur: 0.56, hold: 0.15, ease: 'in' },
        { pose: { torso: 78, nearLeg: [258, 258], nearFoot: 172, nearArm: [239.5, 157] }, dur: 0.21, hold: 0, ease: 'linear', tween: true },
        { pose: { torso: 73, nearLeg: [253, 253], nearFoot: 170.5, nearArm: [212, 171] }, dur: 0.12, hold: 0, ease: 'out', tween: true },
      ],
    },
    alt: {
      name: 'Knee Push-up',
      cue: 'Knees down, body straight from knees to head.',
      equipment: 'none',
      description: 'A figure with knees on the floor keeps a straight line from knees to head while lowering the chest and pressing back up.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearHand', x: 124 },
        focus: ['chest', 'arms'],
        contacts: ['nearHand', 'nearKnee'],
        keys: [
          { pose: { torso: 54.5, nearArm: [190, 190], nearLeg: [234.5, 288], nearFoot: 282 }, dur: 0.15, hold: 0.2, ease: 'in' },
          { pose: { torso: 58, nearLeg: [238, 288.5], nearFoot: 282.5, nearArm: [214, 172] }, dur: 0.26, hold: 0, ease: 'linear', tween: true },
          { pose: { torso: 67.5, nearLeg: [247.5, 290], nearFoot: 284, nearArm: [246.5, 164.5] }, dur: 0.69, hold: 0, ease: 'out', tween: true },
          { pose: { torso: 83, nearLeg: [263, 292], nearFoot: 286, nearArm: [297, 180] }, dur: 0.56, hold: 0.15, ease: 'in' },
          { pose: { torso: 67.5, nearLeg: [247.5, 290], nearFoot: 284, nearArm: [246.5, 164.5] }, dur: 0.21, hold: 0, ease: 'linear', tween: true },
          { pose: { torso: 58, nearLeg: [238, 288.5], nearFoot: 282.5, nearArm: [214, 172] }, dur: 0.12, hold: 0, ease: 'out', tween: true },
        ],
      },
    },
  },
  {
    id: 'wall-push-up',
    name: 'Wall Push-up',
    say: 'Wall push-ups',
    category: 'upper',
    region: 'upper',
    impact: 'low',
    pattern: 'push',
    equipment: 'wall',
    setup: 'Stand facing a wall and place your hands on it at shoulder height.',
    cue: 'Bend your elbows to bring your chest toward the wall.',
    mistake: 'Letting the hips drift back instead of staying in line.',
    description: 'A figure leans into a wall with a straight body, bends the elbows to bring the chest toward the wall, then presses back.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearHand', x: 151.4 },
      focus: ['chest', 'arms'],
      props: [{ type: 'wall', x: 156 }],
      contacts: ['nearToe'],
      keys: [
        { pose: { torso: 22, head: 18, nearLeg: [202, 202], nearFoot: 100, nearArm: [92, 92] }, dur: 0.55, hold: 0.2, ease: 'in' },
        { pose: { torso: 28.5, head: 24.5, nearLeg: [208.5, 208.5], nearFoot: 104, nearArm: [124, 43] }, dur: 0.55, hold: 0, ease: 'out', tween: true },
        { pose: { torso: 35, head: 31, nearLeg: [215, 215], nearFoot: 108, nearArm: [123.5, 11.5] }, dur: 0.45, hold: 0.15, ease: 'in' },
        { pose: { torso: 28.5, head: 24.5, nearLeg: [208.5, 208.5], nearFoot: 104, nearArm: [124, 43] }, dur: 0.45, hold: 0, ease: 'out', tween: true },
      ],
    },
    alt: {
      name: 'Close Wall Push-up',
      cue: 'Stand closer to the wall and bend only partway.',
      equipment: 'wall',
      description: 'A figure stands close to the wall, nearly upright, and bends the elbows a little to lean in, then presses back.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearHand', x: 135.4 },
        focus: ['chest', 'arms'],
        props: [{ type: 'wall', x: 140 }],
        contacts: ['nearToe'],
        keys: [
          { pose: { torso: 10, head: 10, nearLeg: [190, 190], nearFoot: 100, nearArm: [96, 96] }, dur: 0.55, hold: 0.2, ease: 'in' },
          { pose: { torso: 15, head: 15, nearLeg: [195, 195], nearFoot: 100, nearArm: [129.5, 55.5] }, dur: 0.55, hold: 0, ease: 'out', tween: true },
          { pose: { torso: 20, head: 20, nearLeg: [200, 200], nearFoot: 100, nearArm: [140, 34] }, dur: 0.45, hold: 0.15, ease: 'in' },
          { pose: { torso: 15, head: 15, nearLeg: [195, 195], nearFoot: 100, nearArm: [129.5, 55.5] }, dur: 0.45, hold: 0, ease: 'out', tween: true },
        ],
      },
    },
  },
  {
    id: 'pike-push-up',
    name: 'Pike Push-up',
    say: 'Pike push-ups',
    category: 'upper',
    region: 'upper',
    impact: 'low',
    pattern: 'overhead-push',
    equipment: 'none',
    setup: 'Hands and feet on the floor, hips lifted high in an upside-down V.',
    cue: 'Bend your elbows to lower your head toward the floor.',
    mistake: 'Letting the hips drop so it turns into a regular push-up.',
    caution: 'Lower only as far as your shoulders feel steady.',
    description: 'A figure in an upside-down V with hips high bends the elbows back to lower the head toward the floor in front of the hands, then presses up.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearHand', x: 128 },
      focus: ['shoulders', 'arms'],
      contacts: ['nearHand', 'nearToe'],
      keys: [
        { pose: { torso: 130, nearArm: [160, 160], nearLeg: [199.5, 199.5], nearFoot: 125 }, dur: 0.16, hold: 0.2, ease: 'in' },
        { pose: { torso: 132, head: 132, nearLeg: [202, 202], nearFoot: 127, nearArm: [179.5, 143] }, dur: 0.29, hold: 0, ease: 'linear', tween: true },
        { pose: { torso: 137, head: 137, nearLeg: [209, 209], nearFoot: 132, nearArm: [202, 130] }, dur: 0.75, hold: 0, ease: 'out', tween: true },
        { pose: { torso: 145, head: 145, nearLeg: [220.5, 220.5], nearFoot: 140, nearArm: [232.5, 121] }, dur: 0.62, hold: 0.15, ease: 'in' },
        { pose: { torso: 137, head: 137, nearLeg: [209, 209], nearFoot: 132, nearArm: [202, 130] }, dur: 0.24, hold: 0, ease: 'linear', tween: true },
        { pose: { torso: 132, head: 132, nearLeg: [202, 202], nearFoot: 127, nearArm: [179.5, 143] }, dur: 0.14, hold: 0, ease: 'out', tween: true },
      ],
    },
    alt: {
      name: 'Pike Hold',
      cue: 'Hold your hips high and press the floor away.',
      equipment: 'none',
      description: 'A figure holds an upside-down V with straight arms and hips high, breathing steadily.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearHand', x: 128 },
        focus: ['shoulders', 'arms'],
        contacts: ['nearHand', 'nearToe'],
        keys: [
          { pose: { torso: 130, nearArm: [160, 160], nearLeg: [199.5, 199.5], nearFoot: 125 }, dur: 1.8, hold: 0.2 },
          { pose: { torso: 135, nearArm: [155, 155], nearLeg: [198, 198], nearFoot: 128 }, dur: 1.8, hold: 0.2 },
        ],
      },
    },
  },
  {
    id: 'floor-dip',
    name: 'Floor Dip',
    say: 'Floor dips',
    category: 'upper',
    region: 'upper',
    impact: 'low',
    pattern: 'dip',
    equipment: 'none',
    setup: 'Sit with knees bent, hands on the floor behind your hips, fingers forward.',
    cue: 'Lift your hips, then bend your elbows straight back.',
    mistake: 'Letting the shoulders shrug up toward the ears.',
    caution: 'Keep the bend small if the front of your shoulders feels strained.',
    description: 'A seated figure with hands behind the hips and hips lifted bends the elbows straight back to lower, then presses up.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearHand', x: 58 },
      focus: ['arms'],
      contacts: ['nearHand', 'nearToe', 'nearAnkle'],
      keys: [
        { pose: { torso: 323, head: 345, nearFoot: 100, nearArm: [191.5, 174.5], nearLeg: [60, 157.5] }, dur: 0.55, hold: 0.2, ease: 'in' },
        { pose: { torso: 320.5, head: 342.5, nearFoot: 100, nearArm: [215, 166], nearLeg: [50.5, 164.5] }, dur: 0.55, hold: 0, ease: 'out', tween: true },
        { pose: { torso: 318, head: 340, nearFoot: 100, nearArm: [231.5, 168], nearLeg: [41, 170] }, dur: 0.45, hold: 0.15, ease: 'in' },
        { pose: { torso: 320.5, head: 342.5, nearFoot: 100, nearArm: [215, 166], nearLeg: [50.5, 164.5] }, dur: 0.45, hold: 0, ease: 'out', tween: true },
      ],
    },
    alt: {
      name: 'Seated Floor Dip',
      cue: 'Keep your hips down and bend your elbows a little.',
      equipment: 'none',
      description: 'A figure sits with hips on the floor and hands behind, leans back by bending the elbows a little, then presses up to sit tall.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearHand', x: 52 },
        focus: ['arms'],
        contacts: ['nearHand', 'hip', 'nearToe', 'nearAnkle'],
        keys: [
          { pose: { torso: 340, head: 358, nearFoot: 100, nearArm: [206.5, 206.5], nearLeg: [52.5, 137.5] }, dur: 0.55, hold: 0.2, ease: 'in' },
          { pose: { torso: 331, head: 349, nearFoot: 100, nearArm: [225.5, 174], nearLeg: [52.5, 137.5] }, dur: 0.55, hold: 0, ease: 'out', tween: true },
          { pose: { torso: 322, head: 340, nearFoot: 100, nearArm: [231, 156], nearLeg: [52.5, 137.5] }, dur: 0.45, hold: 0.15, ease: 'in' },
          { pose: { torso: 331, head: 349, nearFoot: 100, nearArm: [225.5, 174], nearLeg: [52.5, 137.5] }, dur: 0.45, hold: 0, ease: 'out', tween: true },
        ],
      },
    },
  },
  {
    id: 'shoulder-taps',
    name: 'Shoulder Taps',
    say: 'Shoulder taps',
    category: 'upper',
    region: 'upper',
    impact: 'low',
    pattern: 'plank',
    equipment: 'none',
    setup: 'Start in a high plank with your feet a little wider than your hips.',
    cue: 'Tap the opposite shoulder while keeping your hips still.',
    mistake: 'Rocking the hips from side to side.',
    caution: 'Spread your fingers wide to ease the load on your wrists.',
    description: 'A figure in a high plank lifts one hand to tap the opposite shoulder, sets it down, then taps with the other hand.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearToe', x: 30 },
      focus: ['shoulders', 'core'],
      contacts: ['nearToe'],
      keys: [
        { pose: { torso: 70.5, nearArm: [182, 182], farArm: [182, 182], nearLeg: [250.5, 250.5], nearFoot: 170 }, dur: 0.4, hold: 0.08 },
        { pose: { torso: 70.5, nearArm: [187, 20], farArm: [182, 182], nearLeg: [250.5, 250.5], nearFoot: 170 }, dur: 0.4, hold: 0.14 },
        { pose: { torso: 70.5, nearArm: [182, 182], farArm: [182, 182], nearLeg: [250.5, 250.5], nearFoot: 170 }, dur: 0.4, hold: 0.08 },
        { pose: { torso: 70.5, nearArm: [182, 182], farArm: [187, 20], nearLeg: [250.5, 250.5], nearFoot: 170 }, dur: 0.4, hold: 0.14 },
      ],
    },
    alt: {
      name: 'Knee Shoulder Taps',
      cue: 'Knees down, tap each shoulder with steady hips.',
      equipment: 'none',
      description: 'A figure in a plank on the knees lifts one hand to tap the opposite shoulder, then switches hands.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearKnee', x: 76 },
        focus: ['shoulders', 'core'],
        contacts: ['nearKnee'],
        keys: [
          { pose: { torso: 54, nearArm: [182, 182], farArm: [182, 182], nearLeg: [234, 288], nearFoot: 282 }, dur: 0.4, hold: 0.08 },
          { pose: { torso: 54, nearArm: [171, 4], farArm: [182, 182], nearLeg: [234, 288], nearFoot: 282 }, dur: 0.4, hold: 0.14 },
          { pose: { torso: 54, nearArm: [182, 182], farArm: [182, 182], nearLeg: [234, 288], nearFoot: 282 }, dur: 0.4, hold: 0.08 },
          { pose: { torso: 54, nearArm: [182, 182], farArm: [171, 4], nearLeg: [234, 288], nearFoot: 282 }, dur: 0.4, hold: 0.14 },
        ],
      },
    },
  },
  {
    id: 'plank-up-down',
    name: 'Plank Up-Down',
    say: 'Plank up-downs',
    category: 'upper',
    region: 'upper',
    impact: 'low',
    pattern: 'plank',
    equipment: 'none',
    setup: 'Start in a forearm plank with elbows under your shoulders.',
    cue: 'Press up one hand at a time, then lower one arm at a time.',
    mistake: 'Swinging the hips with each step.',
    caution: 'Move slowly if your wrists or elbows need time to settle.',
    description: 'A figure in a forearm plank places one hand, then the other, to press up into a high plank, then lowers back to the forearms one arm at a time.',
    demo: {
      view: 'side',
      anchor: { joint: 'nearToe', x: 30 },
      focus: ['shoulders', 'core'],
      contacts: ['nearToe'],
      keys: [
        { pose: { torso: 82.5, nearArm: [180, 90], nearLeg: [262.5, 262.5], nearFoot: 176, farArm: [180, 90] }, dur: 0.5, hold: 0.15, ease: 'inOut' },
        { pose: { torso: 81.5, nearLeg: [261.5, 261.5], nearFoot: 175.5, nearArm: [219, 110.5], farArm: [179, 95.5] }, dur: 0.3, hold: 0.05, ease: 'in' },
        { pose: { torso: 76, nearLeg: [256, 256], nearFoot: 174, nearArm: [202, 130], farArm: [202, 130] }, dur: 0.3, hold: 0, ease: 'out', tween: true },
        { pose: { torso: 70.5, nearLeg: [250.5, 250.5], nearFoot: 172, nearArm: [166, 166], farArm: [166, 166] }, dur: 0.3, hold: 0.2, ease: 'in' },
        { pose: { torso: 75.5, nearLeg: [255.5, 255.5], nearFoot: 173.5, nearArm: [190.5, 108], farArm: [199.5, 132.5] }, dur: 0.3, hold: 0, ease: 'out', tween: true },
        { pose: { torso: 81.5, nearLeg: [261.5, 261.5], nearFoot: 175.5, nearArm: [179, 95.5], farArm: [219, 110.5] }, dur: 0.5, hold: 0.05, ease: 'inOut' },
      ],
    },
    alt: {
      name: 'Knee Plank Up-Down',
      cue: 'Knees down, press up one hand at a time.',
      equipment: 'none',
      description: 'A figure on the knees moves from a forearm plank up to straight arms one hand at a time, then lowers back down.',
      demo: {
        view: 'side',
        anchor: { joint: 'nearKnee', x: 70 },
        focus: ['shoulders', 'core'],
        contacts: ['nearKnee'],
        keys: [
          { pose: { torso: 72.5, nearArm: [180, 90], nearLeg: [252.5, 288], nearFoot: 282, farArm: [180, 90] }, dur: 0.5, hold: 0.15, ease: 'inOut' },
          { pose: { torso: 69, nearLeg: [249, 288], nearFoot: 282, nearArm: [214, 114], farArm: [175, 101.5] }, dur: 0.3, hold: 0.05, ease: 'in' },
          { pose: { torso: 62.5, nearLeg: [242.5, 288], nearFoot: 282, nearArm: [197, 128.5], farArm: [197, 128.5] }, dur: 0.3, hold: 0, ease: 'out', tween: true },
          { pose: { torso: 54, nearLeg: [234, 288], nearFoot: 282, nearArm: [160.5, 160.5], farArm: [160.5, 160.5] }, dur: 0.3, hold: 0.2, ease: 'in' },
          { pose: { torso: 63, nearLeg: [243, 288], nearFoot: 282, nearArm: [188, 102.5], farArm: [199.5, 126] }, dur: 0.3, hold: 0, ease: 'out', tween: true },
          { pose: { torso: 69, nearLeg: [249, 288], nearFoot: 282, nearArm: [175, 101.5], farArm: [214, 114] }, dur: 0.5, hold: 0.05, ease: 'inOut' },
        ],
      },
    },
  },
  {
    id: 'prone-y-raise',
    name: 'Prone Y Raise',
    say: 'Prone Y raises',
    category: 'upper',
    region: 'upper',
    impact: 'low',
    pattern: 'pull',
    equipment: 'none',
    setup: 'Lie face down with your arms overhead in a Y, thumbs up.',
    cue: 'Lift your arms a few inches, then lower slowly.',
    mistake: 'Craning the neck up to lift higher.',
    description: 'A figure lying face down with arms overhead lifts both arms a few inches off the floor, pauses, and lowers them.',
    demo: {
      view: 'side',
      anchor: { joint: 'hip', x: 90 },
      focus: ['shoulders', 'back'],
      props: [{ type: 'mat', x1: 8, x2: 192 }],
      contacts: ['hip', 'nearKnee', 'nearToe'],
      keys: [
        { pose: { torso: 87, head: 89, nearArm: [96, 96], farArm: [96, 96], nearLeg: [267, 284], farLeg: [267, 284], nearFoot: 190, farFoot: 190 }, dur: 1, hold: 0.25 },
        { pose: { torso: 82, head: 84, nearArm: [71, 71], farArm: [71, 71], nearLeg: [267, 284], farLeg: [267, 284], nearFoot: 190, farFoot: 190 }, dur: 1, hold: 0.35 },
      ],
    },
    alt: {
      name: 'Single-Arm Y Raise',
      cue: 'Lift one arm at a time, just a few inches.',
      equipment: 'none',
      description: 'A figure lying face down lifts one arm a few inches, lowers it, then lifts the other.',
      demo: {
        view: 'side',
        anchor: { joint: 'hip', x: 90 },
        focus: ['shoulders', 'back'],
        props: [{ type: 'mat', x1: 8, x2: 192 }],
        contacts: ['hip', 'nearKnee', 'nearToe'],
        keys: [
          { pose: { torso: 87, head: 89, nearArm: [96, 96], farArm: [96, 96], nearLeg: [267, 284], farLeg: [267, 284], nearFoot: 190, farFoot: 190 }, dur: 0.8, hold: 0.15 },
          { pose: { torso: 85, head: 87, nearArm: [75, 75], farArm: [96, 96], nearLeg: [267, 284], farLeg: [267, 284], nearFoot: 190, farFoot: 190 }, dur: 0.8, hold: 0.3 },
          { pose: { torso: 87, head: 89, nearArm: [96, 96], farArm: [96, 96], nearLeg: [267, 284], farLeg: [267, 284], nearFoot: 190, farFoot: 190 }, dur: 0.8, hold: 0.15 },
          { pose: { torso: 85, head: 87, nearArm: [96, 96], farArm: [75, 75], nearLeg: [267, 284], farLeg: [267, 284], nearFoot: 190, farFoot: 190 }, dur: 0.8, hold: 0.3 },
        ],
      },
    },
  },
  {
    id: 'superman',
    name: 'Superman',
    say: 'Superman lifts',
    category: 'upper',
    region: 'upper',
    impact: 'low',
    pattern: 'pull',
    equipment: 'none',
    setup: 'Lie face down with your arms reaching overhead.',
    cue: 'Lift your arms, chest and legs gently, then lower.',
    mistake: 'Lifting too high and squeezing the lower back.',
    caution: 'Keep the lift low and comfortable for your lower back.',
    description: 'A figure lying face down lifts the arms, chest and legs a little off the floor, pauses, and lowers them.',
    demo: {
      view: 'side',
      anchor: { joint: 'hip', x: 90 },
      focus: ['back', 'glutes'],
      props: [{ type: 'mat', x1: 8, x2: 192 }],
      contacts: ['hip'],
      keys: [
        { pose: { torso: 87, head: 89, nearArm: [96, 96], farArm: [96, 96], nearLeg: [267, 284], farLeg: [267, 284], nearFoot: 190, farFoot: 190 }, dur: 1, hold: 0.2 },
        { pose: { torso: 79, head: 81, nearArm: [69, 69], farArm: [69, 69], nearLeg: [285, 285], farLeg: [285, 285], nearFoot: 205, farFoot: 205 }, dur: 1, hold: 0.45 },
      ],
    },
    alt: {
      name: 'Alternating Superman',
      cue: 'Lift one arm and the opposite leg, then switch.',
      equipment: 'none',
      description: 'A figure lying face down lifts one arm and the opposite leg a little, lowers them, then switches sides.',
      demo: {
        view: 'side',
        anchor: { joint: 'hip', x: 90 },
        focus: ['back', 'glutes'],
        props: [{ type: 'mat', x1: 8, x2: 192 }],
        contacts: ['hip'],
        keys: [
          { pose: { torso: 87, head: 89, nearArm: [96, 96], farArm: [96, 96], nearLeg: [267, 284], farLeg: [267, 284], nearFoot: 190, farFoot: 190 }, dur: 0.8, hold: 0.15 },
          { pose: { torso: 83, head: 85, nearArm: [73, 73], farArm: [96, 96], nearLeg: [267, 284], farLeg: [283, 283], nearFoot: 190, farFoot: 203 }, dur: 0.8, hold: 0.3 },
          { pose: { torso: 87, head: 89, nearArm: [96, 96], farArm: [96, 96], nearLeg: [267, 284], farLeg: [267, 284], nearFoot: 190, farFoot: 190 }, dur: 0.8, hold: 0.15 },
          { pose: { torso: 83, head: 85, nearArm: [96, 96], farArm: [73, 73], nearLeg: [283, 283], farLeg: [267, 284], nearFoot: 203, farFoot: 190 }, dur: 0.8, hold: 0.3 },
        ],
      },
    },
  },
  {
    id: 'arm-circles',
    name: 'Arm Circles',
    say: 'Arm circles',
    category: 'upper',
    region: 'upper',
    impact: 'low',
    pattern: 'shoulder-mobility',
    equipment: 'none',
    setup: 'Stand tall with your feet hip-width apart.',
    cue: 'Sweep long arms in big, smooth backward circles.',
    mistake: 'Shrugging the shoulders up toward the ears.',
    caution: 'Make the circles smaller if a shoulder feels uncomfortable.',
    description: 'A standing figure, seen from the side, sweeps straight arms up, back, down and forward in big smooth circles.',
    demo: {
      view: 'side',
      anchor: { joint: 'hip', x: 100 },
      focus: ['shoulders'],
      contacts: ['nearToe', 'nearAnkle'],
      keys: [
        { pose: { torso: 0, nearLeg: [168, 192], farLeg: [170, 190], nearFoot: 101, farFoot: 100, nearArm: [90, 90] }, dur: 0.5, hold: 0, ease: 'linear' },
        { pose: { torso: 0, nearLeg: [168, 192], farLeg: [170, 190], nearFoot: 101, farFoot: 100, nearArm: [0, 0] }, dur: 0.5, hold: 0, ease: 'linear' },
        { pose: { torso: 0, nearLeg: [168, 192], farLeg: [170, 190], nearFoot: 101, farFoot: 100, nearArm: [270, 270] }, dur: 0.5, hold: 0, ease: 'linear' },
        { pose: { torso: 0, nearLeg: [168, 192], farLeg: [170, 190], nearFoot: 101, farFoot: 100, nearArm: [180, 180] }, dur: 0.5, hold: 0, ease: 'linear' },
      ],
    },
    alt: {
      name: 'Small Arm Circles',
      cue: 'Arms out to the sides, draw small, slow circles.',
      equipment: 'none',
      description: 'A standing figure, seen from the front, holds both arms out to the sides and moves the hands in small slow circles.',
      demo: {
        view: 'front',
        focus: ['shoulders'],
        contacts: ['nearToe', 'farToe'],
        keys: [
          { pose: { torso: 0, nearArm: [99.5, 102.5], nearLeg: [178, 180] }, dur: 0.4, hold: 0, ease: 'linear' },
          { pose: { torso: 0, nearArm: [104, 107], nearLeg: [178, 180] }, dur: 0.4, hold: 0, ease: 'linear' },
          { pose: { torso: 0, nearArm: [99.5, 102.5], nearLeg: [178, 180] }, dur: 0.4, hold: 0, ease: 'linear' },
          { pose: { torso: 0, nearArm: [90.5, 93.5], nearLeg: [178, 180] }, dur: 0.4, hold: 0, ease: 'linear' },
          { pose: { torso: 0, nearArm: [86, 89], nearLeg: [178, 180] }, dur: 0.4, hold: 0, ease: 'linear' },
          { pose: { torso: 0, nearArm: [90.5, 93.5], nearLeg: [178, 180] }, dur: 0.4, hold: 0, ease: 'linear' },
        ],
      },
    },
  },
];
